from typing import Protocol

from app.schemas.user import AdminUserSummary, User, UserRole


class UserRepository(Protocol):
    def find_by_id(self, user_id: str) -> User | None: ...

    def find_by_email(self, email: str) -> User | None: ...

    def email_exists(self, email: str) -> bool: ...

    def create(self, email: str, hashed_password: str, role: UserRole = "user") -> User: ...

    def admin_exists(self) -> bool: ...

    def authenticate(self, email: str, plain_password: str) -> User | None: ...

    def list_all_with_stats(self) -> list[AdminUserSummary]: ...
